### ISSUE TITLE
Mise en place de nodes pour Hadoop

### ISSUE THREAD

**Issue by ogdabou** [ogdabou/PFA#4]
Evaluer la possibilité d'avoir plusieurs noeuds pour tester Hadoop. Combien ca nous couterait pour faire ces tests

**Comment by Lenjyco** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-hadoop-on-ubuntu-13-10 (CF : vi. Editing /usr/local/hadoop/etc/hadoop/hdfs-site.xml )

hdfs namenode -format -> commande pour mettre à jour le namenodes lorsque l'on ajoute des datanodes pour hadoop
