### ISSUE TITLE
Pouvoir expliquer pour le choix du Random Forest

### ISSUE THREAD

**Issue by ogdabou** [ogdabou/PFA#8]

**Comment by ogdabou** [comment]
http://blog.datadive.net/interpreting-random-forests/

**Comment by ogdabou** [comment]
Julien à dit "Le random forest est adapté aux données avec beaucoup de variables, et c'est le cas des données provenants de transactions de cartes bancaires"

**Comment by Lenjyco** [comment]
Ya des infos dans les liens qui nous permettrons de justifier le choix du rdm forest
